import "./globals.css";

export const metadata = {
  title: "NeuraMate",
  keywords: "AI, NeuraMate, Next.js, React",
  authors: [{ name: "Nanda Kumar" }],
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
